language: node_js
node_js:
- '0.10'
notifications:
  email: false
before_install:
- npm install -g grunt-cli
deploy:
  provider: npm
  email: stephan@thehoodiefirm.com
  on:
    all_branches: true
    tags: true
  api_key:
    secure: jJ+CVdY33nutReZzcMRNzNHDQ5gZaV9WEL4N+3AXnMEXX76f27Z37WXdUVm+uGEGL/Mbh+0zp7jMp02A8OES+QA3oVeAU5j4HZm067pYcGT/jQ+2jvMdGcA2JIWkW12J1IuFszcd9WDmw8QJ8SSfcbLdC04aajytCFQznDSCanY=
env:
  global:
  - secure: YNdasuXo8PwGE1SIgmfT43NLXkyQZBa+suvUMZtDosRYLpbWafC+L4ZOJ51ioF21vWD4mlN3YNGNdAsDSIiXwu6KYuvLtRuLNQ1d7rmNEQ20K3X/EF0aBUu3uUVD3fh3pQ+6BIjmNHkOSlxHm6edDZpg/jdddeQPtfp4B/Ug+wo=
before_deploy:
- grunt before-deploy
after_deploy:
- grunt after-deploy
sudo: false
cache:
  directories:
  - node_modules
