language: node_js
node_js:
- '0.10'
notifications:
  email: false
before_install:
- npm install -g grunt-cli
after_sucess:
- grunt ghrelease
deploy:
  provider: npm
  email: stephan@boennemann.me
  api_key:
    secure: Bjc1wSY4zQsDaLcWeULwffX+QBB1OXEBGUJ+ibpoA1XnsUJw+ydLD/LjNc3WglPzKDbV47f6SxFV0oArZ+1VYaKP/LYDAtvMfV6GFYqxhO5WL/MyDEqhGjho1P332365sfXR6o324J/yPsprJPUeHPivJMSBjz4Gu7LSxZiELBs=
  on:
    all_branches: true
    tags: true
env:
  global:
    secure: k6FGpes0piSDmaQJ5TfqRiOQjeEAVzaGiPKYTsQTPYUn18yVAoe7ulE8itRNcOeJuVS/sUYuvKn3Q4QyMAPdKbMKNAx3PoBbTKtv10uPNuXGC+Rdy9jyWcyK5XGYY03lCSkP6k8r3U/0S8EJx1rEJOwyy4HTOOC4ZuiOOQJL0W8=
